import React, { useState } from 'react'
import './Case_study.css'

const caseStudies = [
  {
    statement: "Discovery of Profits not recognised in ERP",

    problem: {
      heading: "Problem ",
      description: " XYZ Ltd is into business of custom injection molding of plastic items.The company has recently implemented a new ERP system and as per the financial statements generated by the new system, Substantial loss and overall negative net-worth was observed",
    },
    solution: {
      heading: "Solution ",
      description: "Favourable variance (profit) arising due to high standard costs as compared to actual costs which was accumulated in WIP account were transferred to respective accounts (i.e., labor cost, other production cost) resulting in reduction of overall cost of production. An automated process was created for transfer of variance to respective accounts.",
    },
    results: {
      heading: "Results ",
      description: "Profitability was reinstated correctly in P&L account for the period ending on 31st March, 2019 from a loss amounting to Rs. 1 crore to actual profit of Rs. 5 Crore.",
    },
  },
  {
    statement: "Efficient production planning & inventory management",

    problem: {
      heading: "Problem",
      description: "EFG Ltd is into business of manufacturing automobile ancillary spare parts. The company did not maintain color-wise stock of assembly parts and had no record of color-wise production of parts. Production plan was made on the basis of finished goods required for sales, ignoring the stock available of assembly parts.",
    },
    solution: {
      heading: "Solution ",
      description: "Color-wise stock was recorded in the current ERP system post physical stock taking. Color-wise BOM (Bill of Material) masters were created in the system, enabling plant managers to monitor the closing stock of assembly parts and perform efficient production planning.",
    },
    results: {
      heading: "Results ",
      description: "Reduced inventory levels of assembly parts were achieved by avoiding substantial variation in available stock across assembly parts required for each unit of finished product. This led to a reduction in annual inventory carrying cost of Rs. 5,00,000.",
    },
  },
  {
    statement: "Increase Sales without Increase in Cost",

    problem: {
      heading: "Problem ",
      description: "A home décor products & upholstery merchandise company was struggling with retail sales due to lack of product understanding among consumers.A catalogue was need of the hour, but production cost of a catalogue with fabric samples ranges from ₹600-4000.",
    },
    solution: {
      heading: "Solution ",
      description: "Our analysis helped in prioritising key demand areas of the catalog based on product-wise, region-wise analysis of sales data.The company realised higher demand for plain curtains in areas of tourist interest and embroidered curtains in high standard of living areas.",
    },
    results: {
      heading: "Results ",
      description: "Net increase in sales across regions of ₹15,00,000 was achieved without any change in total cost involved in the preparation and distribution of product catalogues.",
    },
  },
  {
    statement: "Improvements in Operational Efficiencies",

    problem: {
      heading: "Problem ",
      description: "ABC Ltd, a manufacturer of plastic furniture, faced challenges in monitoring daily production activities at both the plant and head office level. The reliance on monthly Excel-based MIS, due to the absence of a dedicated production module, led to inefficiencies.Additionally, the MIS format failed to provide accurate insights into product cycle time and overall efficiency across the factory.",
    },
    solution: {
      heading: "Solution ",
      description: "To address these issues, the data collection process was revised to track material rejection during production and hourly production rates.Furthermore, interactive and visually intuitive dashboards were developed, enabling plant managers and executives to monitor real-time data, including cycle time, machine utilization, machine downtime, and production rejection analysis.",
    },
    results: {
      heading: "Results ",
      description: "The implementation of these solutions enhanced monitoring capabilities, reducing product cycle time and improving machine utilization and production output.Additionally, production costs decreased due to better planning and optimized use of available machine hours.",
    },
  },
];



const Case_study = () => {

    const [currentIndex, setCurrentIndex] = useState(0);
    
      const nextSlide = () => {
        setCurrentIndex((prevIndex) =>
          prevIndex === caseStudies.length - 1 ? 0 : prevIndex + 1
        );
      };
    
      const prevSlide = () => {
        setCurrentIndex((prevIndex) =>
          prevIndex === 0 ? caseStudies.length - 1 : prevIndex - 1
        );
      };


  return (
    <div className="case_study_section">
      <div className="upper_case_study">
        <h2>Our Case Studies</h2>
        <p>Discover how we solved real-world problems with innovative solutions.</p>
      </div>

      <div className="bottom_case_study">
        <button className="arrow_ai btn_left" onClick={prevSlide}>&#8249;</button>

        <div className="case_study_wrapper">
          <br />
          <div className="case_study" style={{ transform: `translateX(-${currentIndex * 100}%)` }}>
            {caseStudies.map((study, index) => (
              <div className="case_study_item" key={index}>
                <div className="statement">
                
                {study.statement}

                </div>
               <div className="content_study">
               <div className="problem">
                  <h3>{study.problem.heading}</h3>
                  <p>{study.problem.description}</p>
                </div>
                <div className="solution">
                  <h3>{study.solution.heading}</h3>
                  <p>{study.solution.description}</p>
                </div>
                <div className="results">
                  <h3>{study.results.heading}</h3>
                  <p>{study.results.description}</p>
                </div>
               </div>
              </div>
            ))}
          </div>
        </div>

        <button className="arrow_ai btn_right" onClick={nextSlide}>&#8250;</button>
      </div>
    </div>
  )
}

export default Case_study